## Server Configuration
SERVER_NAME: "convert-service"
SERVER_IP: "127.0.0.1"
SERVER_PORT: "8000"
SERVER_STORE_PATH: "./config/stores"
SERVER_UPLOAD_PATH: "./config/uploads"
SERVER_UPLOAD_LIMIT: 8
SERVER_LOG_LEVEL: "debug"

## Data Configuration
MAX_PAGE_SIZE: 50
MAX_PAGE_LIMIT: 10
CLIENT_BASE_URL: "https://soon1.gear5.io"
CONFIRM_EMAIL_PATH: "/confirm-email"
FORGOT_PASSWORD_PATH: "/forgot-password"

## Database Configuration
DB_DRIVER: "postgres"
DB_HOST: ["172.31.41.108"]
DB_PORT: "5432"
DB_USER: "postgres"
DB_PASSWORD: "!!nika-get-5-million-2023@@"
DB_NAME: "gear5"

# Cache Configuration
LOCAL_CACHE_MAX_COST: 1073741824 #maximum cost of cache (1GB = 2 ^ 30 bits)
LOCAL_CACHE_NUM_COUNTERS: 1e7 #number of keys to track frequency of items (10 milions)
LOCAL_CACHE_BUFFER_ITEMS: 64 #number of keys per get buffer
LOCAL_CACHE_METRICS: true #show statistics

REMOTE_CACHE_DRIVER: "redis"
REMOTE_CACHE_HOST: "172.31.2.129"
REMOTE_CACHE_PORT: "6379"
REMOTE_CACHE_PASSWORD: "0LZLVx3dl8W6FEDrc/iA1yPDn26+3c4Auo1+l/Vud4Bb+Ue9dyp2l1XnUHfuPa8HVrVZ98BljcUkKYuE"
REMOTE_CACHE_NAME: 0

CACHE_ENABLE: true
PRECACHE_ENABLE: true

## Constant configuration
JWT_EXPIRATION_TIME_HOURS: 168 # 7 days
GOOGLE_CLIENT_ID: "505998913719-ia6595esslrq494adpf2iiqgn4vgmsca.apps.googleusercontent.com"
LOG_OUTPUT: "/home/ubuntu/backend/backend-user-gear5/backend-user-gear5.log"
GOOGLE_RECAPTCHA_SECRET: "6Lcab8wjAAAAAKZsk4bWFWqSCo_mYIFJUstBVE7H"

## Storage Configuration
STORAGE_DRIVER: "minio"
STORAGE_USE_SSL: true
STORAGE_ACCESS_KEY: "AKIAQETG7W4XMAXEPWYV"
STORAGE_SECRET_KEY: "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"
STORAGE_REGION: "ap-northeast-1"
STORAGE_BUCKET: "gear5"

## Mail Configuration
MAIL_SENDER: "The Gear5 Team <gear5@nika.guru>"
MAIL_ACCESS_KEY: "AKIAQETG7W4XJVOJ6CT3"
MAIL_SECRET_KEY: "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"
MAIL_REGION: "ap-northeast-1"
